"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.run = run;
const core = __importStar(require("@actions/core"));
const github = __importStar(require("@actions/github"));
const exec = __importStar(require("@actions/exec"));
async function run() {
    try {
        const token = core.getInput('github-token');
        const baselinePath = core.getInput('baseline-path') || 'baseline.json';
        const newPath = core.getInput('new-path') || 'new.json';
        // In production, we would use tool-cache to download the latest binary.
        // For this MVP, we assume the binary is available in the runner environment
        // or we compile it during the workflow setup.
        const binaryPath = core.getInput('binary-path') || './budget-core';
        core.info(`Running Soroban Budget Guard Core against ${baselinePath} and ${newPath}`);
        let output = '';
        let errorOutput = '';
        const options = {};
        options.listeners = {
            stdout: (data) => {
                output += data.toString();
            },
            stderr: (data) => {
                errorOutput += data.toString();
            }
        };
        // Do not throw on non-zero exit so we can still post the comment on regression
        options.ignoreReturnCode = true;
        const exitCode = await exec.exec(binaryPath, ['--baseline', baselinePath, '--new', newPath], options);
        if (errorOutput && exitCode !== 0) {
            core.warning(`Binary stderr: ${errorOutput}`);
        }
        core.info('Command executed successfully. Generating PR comment...');
        // Post the markdown table to the PR
        if (github.context.payload.pull_request) {
            const octokit = github.getOctokit(token);
            const commentBody = `### 📊 Soroban Resource Budget Report\n\n${output}\n\n*Generated by BudgetGate*`;
            await octokit.rest.issues.createComment({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                issue_number: github.context.payload.pull_request.number,
                body: commentBody
            });
            core.info('Successfully posted PR comment.');
        }
        else {
            core.info('Not running in a Pull Request context. Skipping comment generation.');
            // When merging to main, we might want to cache the new.json as baseline.json
            core.info('Tip: In the main branch workflow, use actions/cache to persist new.json as the baseline for future PRs.');
        }
        // Set outputs for subsequent workflow steps
        const hasRegression = output.includes('❌ REGRESSION') || exitCode !== 0;
        core.setOutput('regression_detected', hasRegression.toString());
        if (hasRegression) {
            core.setFailed('Resource cost regression detected! Check the PR comment for details.');
        }
    }
    catch (error) {
        if (error instanceof Error)
            core.setFailed(error.message);
    }
}
if (require.main === module) {
    run();
}
