import * as core from '@actions/core';
import * as github from '@actions/github';
import * as exec from '@actions/exec';
import * as tc from '@actions/tool-cache';
import * as path from 'path';

export async function run(): Promise<void> {
  try {
    const token = core.getInput('github-token');
    const baselinePath = core.getInput('baseline-path') || 'baseline.json';
    const newPath = core.getInput('new-path');
    const fixturePath = core.getInput('fixture-path');
    const rpcUrl = core.getInput('rpc-url');
    let binaryPath = core.getInput('binary-path');
    const binaryVersion = core.getInput('binary-version');
    
    // Download binary if version is specified
    if (binaryVersion && !binaryPath) {
      core.info(`Downloading soroban-budget-core v${binaryVersion}...`);
      const url = `https://github.com/BudgetGate/soroban-budget-core/releases/download/v${binaryVersion}/budget-core-linux-amd64`;
      const downloadPath = await tc.downloadTool(url);
      
      // Cache the tool
      const cachedPath = await tc.cacheFile(downloadPath, 'budget-core', 'soroban-budget-core', binaryVersion);
      binaryPath = path.join(cachedPath, 'budget-core');
      
      // Make it executable
      await exec.exec('chmod', ['+x', binaryPath]);
    } else if (!binaryPath) {
      binaryPath = './budget-core';
    }
    
    core.info(`Running Soroban Budget Guard Core against ${baselinePath}`);
    
    let output = '';
    let errorOutput = '';

    const options: exec.ExecOptions = {};
    options.listeners = {
      stdout: (data: Buffer) => {
        output += data.toString();
      },
      stderr: (data: Buffer) => {
        errorOutput += data.toString();
      }
    };
    
    options.ignoreReturnCode = true;

    const args = ['--baseline', baselinePath];
    if (fixturePath) {
      args.push('--fixture', fixturePath);
      if (rpcUrl) {
        args.push('--rpc-url', rpcUrl);
      }
      // Ensure we output the new snapshot to a file so it can be cached
      args.push('--output-json', 'new.json');
    } else if (newPath) {
      args.push('--new', newPath);
    } else {
      args.push('--new', 'new.json');
    }

    const exitCode = await exec.exec(binaryPath, args, options);

    if (errorOutput && exitCode !== 0) {
      core.warning(`Binary stderr: ${errorOutput}`);
    }

    core.info('Command executed successfully. Generating PR comment...');

    // Set outputs for subsequent workflow steps
    const hasRegression = output.includes('❌ REGRESSION') || exitCode !== 0;

    // Post the markdown table to the PR
    if (github.context.payload.pull_request) {
      const octokit = github.getOctokit(token);
      
      const badgeUrl = hasRegression 
        ? 'https://img.shields.io/badge/BudgetGate-Regression%20Detected-red'
        : 'https://img.shields.io/badge/BudgetGate-Passing-success';
        
      const commentBody = `### 📊 Soroban Resource Budget Report\n\n![BudgetGate Status](${badgeUrl})\n\n${output}\n\n*Generated by BudgetGate*`;
      
      await octokit.rest.issues.createComment({
        owner: github.context.repo.owner,
        repo: github.context.repo.repo,
        issue_number: github.context.payload.pull_request.number,
        body: commentBody
      });
      core.info('Successfully posted PR comment.');
    } else {
      core.info('Not running in a Pull Request context. Skipping comment generation.');
      // When merging to main, we might want to cache the new.json as baseline.json
      if (github.context.ref === 'refs/heads/main' || github.context.ref === 'refs/heads/master') {
        core.info('On main branch. Caching new.json as baseline for future PRs.');
        try {
          // Import here to avoid failing if not installed globally
          const cache = require('@actions/cache');
          // Cache the new.json as the baseline for this commit
          const cacheId = await cache.saveCache(['new.json'], `budgetgate-baseline-${github.context.sha}`);
          core.info(`Saved baseline cache with ID: ${cacheId}`);
        } catch (e) {
          core.warning(`Failed to save baseline cache: ${e}`);
        }
      } else {
        core.info('Tip: In the main branch workflow, use actions/cache to persist new.json as the baseline for future PRs.');
      }
    }

    core.setOutput('regression_detected', hasRegression.toString());

    if (hasRegression) {
      core.setFailed('Resource cost regression detected! Check the PR comment for details.');
    }

  } catch (error) {
    if (error instanceof Error) core.setFailed(error.message);
  }
}

if (require.main === module) {
  run();
}
